AllCops:
  Exclude:
    - "bin/**/*"
    - "node_modules/**/*"
Metrics/ClassLength:
  Exclude:
    - "spec/**/*"
Metrics/LineLength:
  Exclude:
    - "spec/**/*"
Metrics/MethodLength:
  Exclude:
    - "spec/**/*"
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
